=== AshiPal/XML_Project/XMLxsdProject/bin/Movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zensar.com/Movies" xmlns:zen="http://www.zensar.com/Movies" elementFormDefault="qualified">
	<element name="Movies">
		<complexType>
			<sequence>
				<element name="Movie" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="code">
								<simpleType>
									<restriction base="int">
										<totalDigits value="4"></totalDigits>
										<minInclusive value="5001"></minInclusive>
										<maxExclusive value="6000"></maxExclusive>
									</restriction>
								</simpleType>
							</element>
							<element name="title" type="string"></element>
							<element name="release-date" type="date" minOccurs="0" maxOccurs="1"></element>
							<element name="theater-name">
								<simpleType>
									<restriction base="string">
										<minLength value="4"></minLength>
										<maxLength value="20"></maxLength>
									</restriction>
								</simpleType>
							</element>
							<element name="city" minOccurs="0" maxOccurs="unbounded"></element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== AshiPal/XML_Project/XMLxsdProject/bin/moviesDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:Movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/Movies" xsi:schemaLocation="http://www.zensar.com/Movies Movies.xsd ">
  <zen:Movie>
    <zen:code>5004</zen:code>
    <zen:title>Kabir Singh</zen:title>
    <zen:release-date>2019-06-13</zen:release-date>
    <zen:theater-name>PVRCinemas</zen:theater-name>
    <zen:city>Pune</zen:city>
    <zen:city>Bhopal</zen:city>
  </zen:Movie>
  
  <zen:Movie>
    <zen:code>5045</zen:code>
    <zen:title>Arjun Reddy</zen:title>
    <zen:theater-name>Cinepolis</zen:theater-name>
  </zen:Movie>
</zen:Movies>
